<script lang="ts">
    import { sanitize } from "@jill64/universal-sanitizer";
    import type { IOptions } from "sanitize-html";
    //import { marked } from "marked";

    export let text;

    let clean: string | Promise<string> | null = null;

    const defaultConfig: IOptions = {
        allowedTags: [
            // Sections derived from MDN element categories and limited to the more
            // benign categories.
            // https://developer.mozilla.org/en-US/docs/Web/HTML/Element
            // Content sectioning
            "address",
            "article",
            "aside",
            "footer",
            "header",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "hgroup",
            "main",
            "nav",
            "section",
            // Text content
            "blockquote",
            "dd",
            "div",
            "dl",
            "dt",
            "figcaption",
            "figure",
            "hr",
            "li",
            "main",
            "ol",
            "p",
            "pre",
            "ul",
            // Inline text semantics
            "a",
            "abbr",
            "b",
            "bdi",
            "bdo",
            "br",
            "cite",
            "code",
            "data",
            "dfn",
            "em",
            "i",
            "kbd",
            "mark",
            "q",
            "rb",
            "rp",
            "rt",
            "rtc",
            "ruby",
            "s",
            "samp",
            "small",
            "span",
            "strong",
            "sub",
            "sup",
            "time",
            "u",
            "var",
            "wbr",
            // Table content
            "caption",
            "col",
            "colgroup",
            "table",
            "tbody",
            "td",
            "tfoot",
            "th",
            "thead",
            "tr",
        ],
        // Tags that cannot be boolean
        nonBooleanAttributes: [
            "abbr",
            "accept",
            "accept-charset",
            "accesskey",
            "action",
            "allow",
            "alt",
            "as",
            "autocapitalize",
            "autocomplete",
            "blocking",
            "charset",
            "cite",
            "class",
            "color",
            "cols",
            "colspan",
            "content",
            "contenteditable",
            "coords",
            "crossorigin",
            "data",
            "datetime",
            "decoding",
            "dir",
            "dirname",
            "download",
            "draggable",
            "enctype",
            "enterkeyhint",
            "fetchpriority",
            "for",
            "form",
            "formaction",
            "formenctype",
            "formmethod",
            "formtarget",
            "headers",
            "height",
            "hidden",
            "high",
            "href",
            "hreflang",
            "http-equiv",
            "id",
            "imagesizes",
            "imagesrcset",
            "inputmode",
            "integrity",
            "is",
            "itemid",
            "itemprop",
            "itemref",
            "itemtype",
            "kind",
            "label",
            "lang",
            "list",
            "loading",
            "low",
            "max",
            "maxlength",
            "media",
            "method",
            "min",
            "minlength",
            "name",
            "nonce",
            "optimum",
            "pattern",
            "ping",
            "placeholder",
            "popover",
            "popovertarget",
            "popovertargetaction",
            "poster",
            "preload",
            "referrerpolicy",
            "rel",
            "rows",
            "rowspan",
            "sandbox",
            "scope",
            "shape",
            "size",
            "sizes",
            "slot",
            "span",
            "spellcheck",
            "src",
            "srcdoc",
            "srclang",
            "srcset",
            "start",
            "step",
            "style",
            "tabindex",
            "target",
            "title",
            "translate",
            "type",
            "usemap",
            "value",
            "width",
            "wrap",
            // Event handlers
            "onauxclick",
            "onafterprint",
            "onbeforematch",
            "onbeforeprint",
            "onbeforeunload",
            "onbeforetoggle",
            "onblur",
            "oncancel",
            "oncanplay",
            "oncanplaythrough",
            "onchange",
            "onclick",
            "onclose",
            "oncontextlost",
            "oncontextmenu",
            "oncontextrestored",
            "oncopy",
            "oncuechange",
            "oncut",
            "ondblclick",
            "ondrag",
            "ondragend",
            "ondragenter",
            "ondragleave",
            "ondragover",
            "ondragstart",
            "ondrop",
            "ondurationchange",
            "onemptied",
            "onended",
            "onerror",
            "onfocus",
            "onformdata",
            "onhashchange",
            "oninput",
            "oninvalid",
            "onkeydown",
            "onkeypress",
            "onkeyup",
            "onlanguagechange",
            "onload",
            "onloadeddata",
            "onloadedmetadata",
            "onloadstart",
            "onmessage",
            "onmessageerror",
            "onmousedown",
            "onmouseenter",
            "onmouseleave",
            "onmousemove",
            "onmouseout",
            "onmouseover",
            "onmouseup",
            "onoffline",
            "ononline",
            "onpagehide",
            "onpageshow",
            "onpaste",
            "onpause",
            "onplay",
            "onplaying",
            "onpopstate",
            "onprogress",
            "onratechange",
            "onreset",
            "onresize",
            "onrejectionhandled",
            "onscroll",
            "onscrollend",
            "onsecuritypolicyviolation",
            "onseeked",
            "onseeking",
            "onselect",
            "onslotchange",
            "onstalled",
            "onstorage",
            "onsubmit",
            "onsuspend",
            "ontimeupdate",
            "ontoggle",
            "onunhandledrejection",
            "onunload",
            "onvolumechange",
            "onwaiting",
            "onwheel",
        ],
        disallowedTagsMode: "discard",
        allowedAttributes: {
            a: ["href", "name", "target"],
            // We don't currently allow img itself by default, but
            // these attributes would make sense if we did.
            img: [
                "src",
                "srcset",
                "alt",
                "title",
                "width",
                "height",
                "loading",
            ],
        },
        //allowedEmptyAttributes: ["alt"],
        // Lots of these won't come up by default because we don't allow them
        selfClosing: [
            "img",
            "br",
            "hr",
            "area",
            "base",
            "basefont",
            "input",
            "link",
            "meta",
        ],
        // URL schemes we permit
        allowedSchemes: ["http", "https", "ftp", "mailto", "tel"],
        allowedSchemesByTag: {},
        allowedSchemesAppliedToAttributes: ["href", "src", "cite"],
        allowProtocolRelative: true,
        enforceHtmlBoundary: false,
        parseStyleAttributes: true,
    };

    const customConfig: IOptions = {
        ...defaultConfig,
        allowedTags: [...(defaultConfig.allowedTags || []), "video", "track"],
        allowedAttributes: {
            ...defaultConfig.allowedAttributes,
            div: ["class"],
            h1: ["class"],
            h2: ["class"],
            video: ["class", "src", "autoplay", "muted", "loop", "controls"],
            track: ["kind"],
        },
        allowedSchemes: ["http", "https"],
    };

    text = `<h2 class='text-xl font-semibold mb-2'>Introduction</h2>

            <div class='mb-4'>In this article, we review some important history and features of Bitcoin for newcomers. We also look at how Bitcoin enables financial sovereignty and freedom. Finally, we explore the challenges facing Bitcoin and its future potential.</div>

            <h2 class='text-xl font-semibold mb-2'>The Bitcoin network</h2>

            <div class='mb-4'>Bitcoin the network officially started on January 3, 2009, when the pseudonymous developer Satoshi Nakamoto created the first block of the Bitcoin blockchain.</div>

            <div class='mb-4'>The Bitcoin blockchain is the public ledger that records all historic transactions. Satoshi received the first 50 bitcoins (BTC), the network's token asset, as a reward for mining this block. Since then, over 840,000 blocks have been added, resulting in over 19 million bitcoins, all created through mining.</div>

            <div class='mb-4'>There are four main players in the Bitcoin network: developers, full nodes, miners, and bitcoin users.</div>

            <div role="alert" class="alert bg-white shadow-lg rounded-2xl border-2 border-purple-100 hover:border-purple-500">
                <div>
                    <h3 class="font-bold">Developers</h3>
                    Developers write the open source code for Bitcoin, which implements rules, such as what is a valid transaction, how a block of transactions should be added to the blockchain, and how miners are rewarded with new bitcoins. They publish their code and anyone else can take that code for free and modify or use it.
                </div>
            </div>
    `;
    try {
        if (text) {
            clean = sanitize(text, {
                sanitizeHtml: customConfig,
            });
        }
    } catch (e) {
        console.error((e as Error).message);
        clean = null;
    }
</script>

<div class="mt-2 font-light leading-relaxed">
    {#if clean}
        {@html clean}
    {/if}
</div>

<style>
</style>
